#!/bin/bash

cd $(dirname $0)

if ! gem list | grep 'bundler' > /dev/null; then
  sudo gem install bundler
fi

#TODO: use rbenv
if ! gem list | grep 'homesick' > /dev/null; then
  sudo gem install homesick
fi

#install gems
bundle install

#execute itamae
if [ "$(uname)" == 'Darwin' ]; then
  bundle exec itamae local recipes/setup.rb -y nodes/local.yml -l debug
elif [ "$(expr substr $(uname -s) 1 5)" == 'Linux' ]; then
  bundle exec itamae local recipes/setup_linux.rb -y nodes/local_linux.yml -l debug
else
  echo "Your platform ($(uname -a)) is not supported."
  exit 1
fi
