brew:
  enable_update: false
  enable_upgrade: false
  add_repositories:
    - homebrew/dupes
    - homebrew/versions
    - homebrew/binary
    - neovim/homebrew-neovim
    - sanemat/font
  install_packages:
    - caskroom/cask/brew-cask
    - coreutils
    - findutils
    - gawk
    - autoconf
    - readline
    - openssl
    - zsh
    - mobile-shell
    - tmux
    - reattach-to-user-namespace
    - vim
    - lv
    - git
    - hub
    - tig
    - ghq
    - git-flow
    - imagemagick
    - expect
    - wget
    - w3m
    - rsync
    - curl
    - openssl
    - readline
    - markdown
    - jq
    - redis
    - mongodb
    - mysql
    - python
    - python3
    - the_silver_searcher
    - android-sdk
    - neovim
    - --powerline --vim-powerline ricty
  install_apps:
    - google-chrome
    - iterm2
    - bettertouchtool
    - alfred
    - 1password
    - xbench
    - vlc
    - parallels-desktop
    - dropbox
    - scroll-reverser
    - path-finder
    - karabiner
    - android-studio
homesick:
  castles:
    - uskanda/dotfiles
login_shell: /usr/local/bin/zsh
